export const FETCH_MOVIE_LIST_REQUEST = 'FETCH_MOVIE_LIST_REQUEST';
export const FETCH_MOVIE_LIST_SUCCESS = 'FETCH_MOVIE_LIST_SUCCESS';
export const FETCH_MOVIE_LIST_FAILED = 'FETCH_MOVIE_LIST_FAILED';

export const POST_MOVIE_LIST_REQUEST = 'POST_MOVIE_LIST_REQUEST';
export const POST_MOVIE_LIST_SUCCESS = 'POST_MOVIE_LIST_SUCCESS';
export const POST_MOVIE_LIST_FAILED = 'POST_MOVIE_LIST_FAILED';

export const SELECT_MOVIE_REQUEST = 'SELECT_MOVIE_REQUEST';
export const SELECT_MOVIE_SUCCESS = 'SELECT_MOVIE_SUCCESS';
export const SELECT_MOVIE_FAILED = 'SELECT_MOVIE_FAILED';

export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';

export const FETCH_FAVORITE_REQUEST = 'FETCH_FAVORITE_REQUEST';
export const FETCH_FAVORITE_SUCCESS = 'FETCH_FAVORITE_SUCCESS';
export const FETCH_FAVORITE_FAILED = 'FETCH_FAVORITE_FAILED';


